### ISSUE TITLE
Set variables in one stage, reuse in a later stage

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-cmd#145]
Example usage case:

```yaml
check-version:
  dotnet:
	  container:
		  image: ubuntu:20.04
			output-vars:
			  dotnet-version:
					type: string
			cmds:
			  - ./check-dotnet-version.sh > ${WHARF_VARS}/dotnet-version

build:
	dotnet:
		docker:
			file: Dockerfile
		  args:
			  - BASE_IMAGE=mcr.microsoft.net/dotnet/sdk:${dotnet-version}
```

Everything here should be discussed or written into an RFC. The type-safety of declaring the `output-vars` is needed to let the wharfyml parsing package understand where the `dotnet-version` variable is coming from statically.
