### ISSUE TITLE
Run stage on condition, e.g if previous failed

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-cmd#146]
Allowing conditions would be grand, such as:

```yaml
failing-stage:
  my-step:
	  container:
		  image: ubuntu:20.04
		  cmds:
			  - echo "writing to non-existing file should fail" > /non/existing/file

runs-on-success:
	# The following condition should be applied by default:
	runs: on-success

  my-step:
	  container:
		  image: ubuntu:20.04
		  cmds:
			  - echo "this only runs when all previous stages succeed"

runs-on-fail:
	runs: on-fail

  my-step:
	  container:
		  image: ubuntu:20.04
		  cmds:
			  - echo "this only runs when any previous stage fails"

runs-on-fail:
	runs: always

  my-step:
	  container:
		  image: ubuntu:20.04
		  cmds:
			  - echo "this always runs, no matter if previous stages fails or not"
```

The `runs` field isn't that nice, so that should be workshopped. Would be nice to consider how to make it future-proof for other conditions we could want to add, such as "only if variable has specific value", "today is a wednesday", etc

The "run if failed" condition is quite different than "skip this step", as it makes it run when it otherwise wouldn't, while other conditions would make it skip when it would otherwise run.

**Comment by Alexamakans** [comment]
I've assigned myself to this, but will probably spend some time thinking about the implementation.

Since I don't a lot of exposure as to what would be nice when it comes to using this feature, I'm very open to different suggestions regarding all of it, probably with focus on what level of flexibility I should aim for, as I could probably easily go overboard there.

If anybody has any good examples, or maybe some do's and don'ts for this kind of thing, that would be extremely helpful I believe.

**Comment by jilleJr** [comment]
Suggest looking at how others do it. Such as CircleCI that has the `when` property, e.g:

```yaml

steps:
  - run:
      name: Testing application
      command: make test
      shell: /bin/bash
      working_directory: ~/my-app
      no_output_timeout: 30m
      environment:
        FOO: bar

  - run: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts

  - run: |
      sudo -u root createuser -h localhost --superuser ubuntu &&
      sudo createdb -h localhost test_db

  - run:
      name: Upload Failed Tests
      command: curl --data fail_tests.log http://example.com/error_logs
      when: on_fail
```

https://circleci.com/docs/2.0/configuration-reference/#ending-a-job-from-within-a-step
