### ISSUE TITLE
Add way to `helm uninstall`

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-cmd#152]
Suggest to use similar "action" field as the kubectl step type.

Eg:

```yaml
my-stage:
  my-step:
	  helm:
		  action: uninstall
			name: my-release
			namespace: prod
			cluster: cluster-config
```

All the flags needs to be evaluated how they should fit in here. The chartVersion flag isn't compatible with uninstalling, to begin with.

Suggested hard-coded valid enum values for the `action` field:

- `upgrade --install` (default)
- `upgrade`
- `install`
- `uninstall`

Maybe we want to support more? Such as also:

- `rollback`
- `test`
- `lint`

Do we have a bunch of statements on all fields like "can only be used on action `upgrade`, `upgrade --install`, ..." or do we have a more dynamic method of declaring fields? Goes together a little with #141
