### ISSUE TITLE
Doesn't run env-less stages if env is specified

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-cmd#158]
If specifying an environment, env-less stages should still run.

E.g:

```yaml
# .wharf-ci.yml

environments:
  my-env: {}

stage-1:
  my-step:
    container:
      image: ubuntu:20.04
      cmds: [ echo hello ]

stage-2:
  environments: [ my-env ]
  my-step:
    container:
      image: ubuntu:20.04
      cmds: [ echo hello ]
```

```console
$ wharf run -e my-env -s stage-1
[INFO ] Starting build.
[WARN ] No stages to run.  stages=0/0
[ERROR] build failed
```
