### ISSUE TITLE
Add templating to pods by wharf-cmd-provisioner

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-cmd#24]
> Depends on:
> - #10

## Requirements

- Configs to change:
	- image used for init container
	- image used for main container
	- resource limits & requests for containers
	- extra env vars
	- extra volumes
	- security contexts
	- etc

Sample config:

```yaml
# wharf-cmd-config.yaml

provisioner:
	kubernetesWorker:
		extraEnvs:
			- name: MY_ENV_VAR
			  value: my env value
		initContainer:
			image: ubuntu:20.04
			cmds:
				- /bin/bash
				- -c
				- |
				  echo "Hello world!"
			resources:
				limits:
					cpu: 100m
					memory: 100Mi
```

## Out of scope (don't focus on this yet)

- Docker support.
