### ISSUE TITLE
Implement variable substituion

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-cmd#54]
The `.wharf-ci.yml` parsing and step type logic currently are lacking variable substitution.

I.e, the following does not work yet:

```yaml
# .wharf-ci.yml

environments:
  myEnv:
    myVar: hello world

myStage:
  environments: [myEnv]
  myStep:
    container:
      image: ubuntu
      cmds:
        - echo ${myVar}
```

This should have support for multiple variable substitution sources to allow substituting from inputs, environment, and built-in vars.

## Out of scope (don't focus on this yet)

- Reading built-in variables. Continued in #55
