### ISSUE TITLE
Lacking varsub in referenced files

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-cmd#72]
> Depends on:
> - #55 

Need varsub support in kubectl and helm referenced files.

Ex:

```yaml
# .wharf-ci.yml
inputs:
  - name: myVar
    type: string
    default: lorem ipsum

myStage:
  myStep:
    helm:
      # ...
      files:
        - values.yaml
```

```yaml
# values.yaml

foo: ${myVar}
```

Should then have variable substitution applied and result in the same as the following `values.yaml` file:

```yaml
# values.yaml

foo: lorem ipsum
```

Compared to the YAML substitution performed inside `.wharf-ci.yml`, this should instead work on a per-line basis and only do crude variable substitution. In `.wharf-ci.yml` it preserves the YAML types, but in these referenced files it should not perform any YAML parsing. This is mostly due to keeping backward compatibility, as some existing build pipelines depend on this behaviour.

Such as:

```yaml
# .wharf-ci.yml
inputs:
  - name: myVar
    type: choice
    default: '{"lorem": "ipsum"}'
    values:
    - '{"lorem": "ipsum"}'
    - '{"foo": "bar"}'
    - '{}'

myStage:
  myStep:
    helm:
      # ...
      files:
        - values2.yaml
```

```yaml
# values2.yaml

myObj: ${myVar}
```

Should become:

```yaml
# values2.yaml

myObj: {"lorem": "ipsum"}

# which is equivalent to:
myObj:
  lorem: ipsum
```

and not:

```yaml
# values2.yaml

myObj: >-
  {"lorem": "ipsum"}
```
