### ISSUE TITLE
Add configs via wharf-core/pkg/config

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-cmd#99]
We need configurability in wharf-cmd

Should use the `pkg/config` package from wharf-core, so we use the same everywhere in all Wharf projects.

Wharf-core is using Viper, and Cobra does have Viper integration, but as this integration isn't exposed then we should just keep the integration manual for now.

There's a lot of hard-coded values in wharf-cmd, just look for TODO's. Extract all that can be found into config. If we miss some things that should be configurable, we can always add it in later.

To not have things collide, we should have separate configs for the different components of wharf-cmd, such as:

```yaml
# ~/.config/iver-wharf/wharf-cmd/wharf-cmd-config.yml
worker:
  k8s:
    context: foobar
    namespace: default

  steps:
    docker:
      kaniko-image: gcr.io/kaniko-project/executor:v1.7.0
    kubectl:
      kubectl-image: docker.io/wharfse/kubectl:v1.23.5
    helm:
      helm-image: docker.io/wharfse/helm:v3.8.1

provisioner:
  k8s:
    context: null
    namespace: wharf-cmd

aggregator:
  wharfApiUrl: http://wharf-api:8080
  wharfCmdProvisionerUrl: http://wharf-cmd-provisioner:8080
```

The format of the config is not final! It's just a brainstorm mockup.
